# Generated by Django 3.2.22 on 2023-10-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Major Service', 'Major Service'), ('Minor Service', 'Minor Service'), ('MOT', 'MOT'), ('Tyre Change', 'Tyre Change')], max_length=75)),
                ('job_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Underway', 'Underway'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='../default_job', upload_to='images/')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
