# Generated by Django 3.2.22 on 2023-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20231018_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_filter',
            field=models.CharField(choices=[('normal', 'Normal')], default='normal', max_length=50),
        ),
    ]
